### ISSUE TITLE
missing code

### ISSUE THREAD

**Issue by micahscopes** [pimvdb/Plomplex#1]
The only code posted right now is the index splash page.  I would like to try adding some functions (for example, doubly periodic functions) so it'd be awesome if the code was available!

**Comment by pimvdb** [comment]
Oh, I'm sorry. I initially hosted the app at GitHub pages but have since switched to Nodester. When v1.4 is ready (that should be very soon) I'll sync this repo with Nodester (and thus the updated code).

(For the record, an old version is available at the `gh-pages` branch - the splash page on `master` was a mistake, I guess.)

**Comment by micahscopes** [comment]
awesome!  can't wait!

**Comment by pimvdb** [comment]
OK, it seems like I am finally at the same wavelength as git... I created a `v1.4` branch which contains the code.
